# Generated by Django 5.1.4 on 2025-01-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Science', 'science'), ('Defence', 'defence'), ('IT', 'it'), ('International', 'international'), ('Healthcare', 'healthcare')], default='science', max_length=100),
        ),
    ]
