# Generated by Django 5.1.4 on 2025-01-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
