# Generated by Django 5.1.4 on 2025-01-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
